/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "wjkceccwfkfevdbijvkh"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indqa2NlY2N3ZmtmZXZkYmlqdmtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc0NDM5NDksImV4cCI6MjA5MzAxOTk0OX0.7-Wl5hglwCi6thpabb2l_n48nnbG98-AFmcIvCu9_pA"